In [ ]:
TASK 1

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
#3*3 matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
square = matrix**2
print(square)

#row-wise sum
row_sum = np.sum(matrix, axis=1)
print(row_sum)


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[ 6 15 24]


Task 2

In [ ]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df.head())
average_scores = df.groupby('gender')['score'].mean(numeric_only=True)
print("Average scores grouped by gender:")
print(average_scores)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

Task 3

In [ ]:
import pandas as pd

# Load CSV file
df = pd.read_csv("data.csv")
df.fillna(df.mean(numeric_only=True),inplace = True)
print(df.head())


Task 4

In [ ]:
a = 12.3
b = 78.78
c = int(a+b)
print(c)

91


task 5

In [ ]:
import pandas as pd
df = pd.read_csv("data.csv")
df.fillna(df.mean(numeric_only=True), inplace=True)
float_cols = df.select_dtypes(include='float').columns
for col in float_cols:
    df[col] = df[col].round().astype(int)
print(df.head())



Task 6

In [ ]:
import pandas as pd
df = pd.read_csv("data.csv")
filtered = df[df["score"] > 90]
sorted_df = filtered.sort_values("score", ascending=False)
print(sorted_df.head())



Task 7

In [ ]:
import pandas as pd
df = pd.read_csv("data.csv")
Q1 = df['score'].quantile(0.25)
Q3 = df['score'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = (Q3 + 1.5*IQR)
outliers = df[(df["score"] >= lower) & (df["score"] <= upper)]
print(outliers)

Task 8

In [ ]:

import pandas as pd
df = pd.DataFrame({
    'name': ['Ali123', 'M!na', 'Ahmad@45', 'Z@in_07']})
df['clean_name'] = df['name'].str.replace(r"[^a-zA-Z\s]", "", regex=True)
print(df)
